# examples:
#   periodic_cleanup:
#     class: CleanSoftDeletedRecordsJob
#     queue: background
#     args: [ 1000, { batch_size: 500 } ]
#     schedule: every hour
#   periodic_cleanup_with_command:
#     command: "SoftDeletedRecord.due.delete_all"
#     priority: 2
#     schedule: at 5am every day

# Course synchronization jobs for all environments
default: &default
  courses_daily_sync:
    class: CoursesSyncJob
    args: ['update']
    schedule: "0 2 * * *"  # Daily at 2 AM
    
  courses_weekly_maintenance:
    class: CoursesSyncJob
    args: ['update']
    schedule: "0 3 * * 0"  # Weekly on Sunday at 3 AM

development:
  <<: *default

production:
  <<: *default
  clear_solid_queue_finished_jobs:
    command: "SolidQueue::Job.clear_finished_in_batches(sleep_between_batches: 0.3)"
    schedule: every hour at minute 12
